# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gene_finder',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/gene_finder',
                'lib_path': 'gene_finder'},
  'syms': {'gene_finder.core': {'gene_finder.core.test_mmseq': ('core.html#test_mmseq', 'gene_finder/core.py')}}}
