"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['test_mmseq']

# %% ../nbs/00_core.ipynb 3
def test_mmseq():
    # Source - https://stackoverflow.com/a
    # Posted by EmmEff, modified by community. See post 'Timeline' for change history
    # Retrieved 2025-11-14, License - CC BY-SA 4.0
    p = subprocess.Popen('mmseqs', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    for line in p.stdout.readlines():
        print (line)
        break
    retval = p.wait()
    print(retval)
